### ISSUE TITLE
A typo in repo description 

### ISSUE THREAD

**Issue by gtluszcz** [SkalskiP/sport#1]
I think you've made a typo in repo description. `Examples of using Computer Vision in a (here ->)spot ⚽🏃`. I assume you want to share this repo with a broader audience. Please don't feel offended. Happens to everyone ;)

**Comment by SkalskiP** [comment]
Oh! Hi, @gtluszcz 👋🏻! How are you? Oh no, I'm definitely not offended. The whole repo was created quite fast. Thanks for pointing that out :)
